name: "Close stale issues and PR"
on:
  schedule:
    - cron: "0 * * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v10
        with:
          stale-issue-message: >
            This issue is stale because it has been open 15 days with no activity. Remove stale label or comment or this will be closed in 5 days.
          close-issue-message: >
            This issue was closed because it has been stalled for 5 days with no activity.
          days-before-stale: 15
          days-before-close: 5
          days-before-pr-stale: -1
          days-before-pr-close: -1
          exempt-issue-labels: "documentation,bug,enhancement"
